### PR TITLE
feat(webapp): Create re-usable generic list component

### LINKED ISSUE #85: [Webapp] Create Generic List Item Template
**Is your feature request related to a problem? Please describe.**
Currently there are a lot of modules that all should have the same basic style and theming, therefore, there should be a standard library component for basic list items for all modules.

**Describe the solution you'd like**
There should be a standard list item that takes in the following props and update the display based on the values provided:

- key (string)
- line1 (string)
- line2 (string | undefined)
- multiline (boolean | undefined)
- icon (Component | undefined)
- detailedViewLink (string | undefined)
- deleteEndpoint (string | undefined)

### LINKED ISSUE #87: [Webapp] Create Generic List Page Template
**Is your feature request related to a problem? Please describe.**
Currently there are a lot of modules that all should have the same basic style and theming, therefore, there should be a standard library component that handles the list/create/delete process for all modules.

**Describe the solution you'd like**
There should be a standard page template that takes in the following props and update the display based on the values provided:

- pageTitle (string)
- child (Component)
- createNewRoute (string | undefined)

### PR DESCRIPTION
**Pull request by nicksinishtaj**
Closes #85
Closes #87

### CODE REVIEW

**Comment by nicksinishtaj** [comment]
Screenshot 2021-03-15 012859

**Comment by nicksinishtaj** [comment]
Couple issues we need to write up stemming from this PR:

**1. ** We need to allow internal API requests to succeed without authorizing a user, for the demo video attached to work we needed to add public: execute to all the stpm/company endpoints
**2. ** For the icons, right now I'm just displaying a business icon for each company, we can potentially look into saving an icon as part of the company schema but this is a more of a "nice to have"

**Comment by nicksinishtaj** [comment]
https://user-images.githubusercontent.com/51200213/111409927-32d23300-86ae-11eb-828f-2db2ec21f227.mp4

**Review by andrewdimmer — APPROVED** [review]
We'll likely want to revisit some this later (for example cleaning up multiline support, switching to icon buttons, etc.), but this is all working as it is now, so we'll get this merged to it's not blocking for other UI components.

**Pull request merged**
